### ISSUE TITLE
Update session submission form

### ISSUE THREAD

**Issue by enockseth** [LinuxAccra-UserGroup/SFD2024#10]
The [form](https://docs.google.com/forms/d/e/1FAIpQLSddXxs_n-g7scPPgLX2lTe3uFRSDpXggJCOi2y2u7QgU490Pg/viewform) does not have a field for:
- session description
- consent for sessions to be recorded or live streamed

**Comment by laudb** [comment]
Great catch @enockseth, it's updated now :100:
