### ISSUE TITLE
Video streaming and recorded sessions

### ISSUE THREAD

**Issue by enockseth** [LinuxAccra-UserGroup/SFD2024#11]
Do we have plans to live stream or published sessions that have permissions to be recorded or live streamed?

**Comment by laudb** [comment]
Yes, I added livestreaming to the list of things planned

**Comment by enockseth** [comment]
I have started a wiki at https://github.com/LinuxAccra-UserGroup/SFD2024/wiki/Video-recording-streaming 

We can look at it and have a very simple setup

**Comment by laudb** [comment]
@enockseth I appreciate this, will take a look and touch base, will see who we can assign this to.

**Comment by laudb** [comment]
Hi @bharaniyhao kindly get in touch with @enockseth on this, include me in any communication.

**Comment by enockseth** [comment]
Service provider to be contracted!
