### ISSUE TITLE
Add 5 minutes gap between each schedule

### ISSUE THREAD

**Issue by enockseth** [LinuxAccra-UserGroup/SFD2024#12]
schedule looks too tight, https://github.com/LinuxAccra-UserGroup/SFD2024/wiki/Program-Outline

**Comment by laudb** [comment]
okay, the idea was to use the breaks to space out the program, where do you think could be adjusted further?

**Comment by laudb** [comment]
ah, just saw the title my bad :sweat_smile:

**Comment by laudb** [comment]
so reviewing it I can add two 5 minutes gaps in the overall schedule, specifically between Presentation 1 & 2 and then between Presentation 3 & 4, what do you think?
