### ISSUE TITLE
Request: create subdomain ==> sfd24.linuxaccra.org

### ISSUE THREAD

**Issue by enockseth** [LinuxAccra-UserGroup/SFD2024#2]
See https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by enockseth** [comment]
Hi @rexfordnyrk, please any updates on this? cc @laudb

**Comment by rexfordnyrk** [comment]
@laudb I have completed this. however, it seems the page need some work because instead of seeing the site on http://sfd24.linuxaccra.org/ you would rather get a 404.

**Comment by laudb** [comment]
@rexfordnyrk oh okay I think I know why, a few more steps on the github side.

**Comment by rexfordnyrk** [comment]
Sure, @enockseth you can close this issue then.

**Comment by enockseth** [comment]
Thank you @rexfordnyrk
