### ISSUE TITLE
Fix map ==> "Have Questions? Get in touch" section

### ISSUE THREAD

**Issue by enockseth** [LinuxAccra-UserGroup/SFD2024#6]
- [x]  OpenStreetMap not Open Street Map
- [x] Add marker for GI-KACE, increase zoom and center map on GI-KACE
 <img src="https://github.com/user-attachments/assets/2797d012-18ef-42ae-b4e1-00e19322d47c" width="40%"/>

**Comment by laudb** [comment]
@enockseth just remembered the event is on the maps for [digitalfreedoms website](https://digitalfreedoms.org/en/software-freedom-day/events/software-freedom-day-2024-laug-accra-ghana) maybe we should switch to that map instead as it's already showing events around the world, what do you think?

**Comment by enockseth** [comment]
I will propose removing the entire section and menu entry for `Contact`. https://github.com/LinuxAccra-UserGroup/SFD2024/blob/621b98da6ec5fc9bb78ea4c2aa1270362a705fbd/index.html#L641 

then link change 
https://github.com/LinuxAccra-UserGroup/SFD2024/blob/621b98da6ec5fc9bb78ea4c2aa1270362a705fbd/index.html#L785
`Our Maps` to `On Maps` and hyperlink to https://osm.org/go/ar~24gH81?m=
